import { Invoice, InvoiceStatus } from "../types";

export const dummyInvoices: Invoice[] = [
  {
    id: "inv-dummy-001",
    invoiceNumber: "PRM/25-26/001",
    client: {
      id: "client-dummy-001",
      name: "Shree Hanuman Metaforge (India)Pvt.Ltd",
      email: "",
      address: "Bamunara industrial Area, Paschim Bardhaman Durgapur, 713212",
      gstin: "19AAGCS5104A1ZS",
      state: "West Bengal",
      stateCode: "19",
    },
    shippingDetails: {
      name: "Shree Hanuman Metaforge (India)Pvt.Ltd",
      address: "Bamunara industrial Area, Paschim Bardhaman Durgapur, 713212",
      gstin: "19AAGCS5104A1ZS",
      state: "West Bengal",
      stateCode: "19",
    },
    items: [
      {
        id: "item-1",
        description: "70% ALUMINA HANGER BRICK",
        hsnCode: "690210",
        uom: "NOS",
        quantity: 280,
        unitPrice: 525,
      },
      {
        id: "item-2",
        description: "70% ALUMINA SHOULDER BRICK",
        hsnCode: "690210",
        uom: "NOS",
        quantity: 240,
        unitPrice: 500,
      },
      {
        id: "item-3",
        description: "70% ALUMINA BRICK",
        hsnCode: "690210",
        uom: "NOS",
        quantity: 1200,
        unitPrice: 110,
      },
      {
        id: "item-4",
        description: "INSULATION BRICK",
        hsnCode: "690320",
        uom: "NOS",
        quantity: 800,
        unitPrice: 31.5,
      },
      {
        id: "item-5",
        description: "WHYTHEAT K",
        hsnCode: "381600",
        uom: "MT",
        quantity: 1,
        unitPrice: 30000,
      },
      {
        id: "item-6",
        description: "ACCOSET 50",
        hsnCode: "690320",
        uom: "BAG",
        quantity: 25,
        unitPrice: 700,
      },
      {
        id: "item-7",
        description: "CERAMICS BLANKET 96",
        hsnCode: "381600",
        uom: "BOX",
        quantity: 7,
        unitPrice: 1250,
      },
      {
        id: "item-8",
        description: "BAR",
        hsnCode: "456789",
        uom: "SET",
        quantity: 100000,
        unitPrice: 200,
      },
      {
        id: "item-9",
        description: "BAR",
        hsnCode: "456789",
        uom: "SET",
        quantity: 100000,
        unitPrice: 200,
      },
      {
        id: "item-10",
        description: "BAR",
        hsnCode: "456789",
        uom: "SET",
        quantity: 100000,
        unitPrice: 200,
      },
    ],
    issueDate: "20/11/2025",
    dueDate: "20/11/2025",
    status: InvoiceStatus.Draft,
    transportMode: "Road",
    vehicleNo: "WB40AU2596",
    dateOfSupply: "20/11/2025",
    placeOfSupply: "Durgapur",
    orderNo: "1234562131",
    taxPayableOnReverseCharge: false,
    cgstRate: 9,
    sgstRate: 9,
    igstRate: 0,
    grLrNo: "465489794521",
    eWayBillNo: "546548898641WED32",
    bankDetails: {
      accountName: "PARAGON REFRACTORIES & MINERALS",
      accountNumber: "758601010050048",
      bankName: "UNION BANK OF INDIA",
      branch: "CITY CENTRE , DURGAPUR",
      ifsc: "UBIN0815187",
    },
    termsAndConditions:
      "1. Goods once sold will not be taken back.\n2. Interest @18% p.a. will be charged if the payment is not made within the stipulated time.",
    jurisdiction: "DURGAPUR",
  },
];
